<?php
define('_DB_SERVER_', 'sql308.byethost22.com');
define('_DB_NAME_', 'b22_15379008_giayit');
define('_DB_USER_', 'b22_15379008');
define('_DB_PASSWD_', 'P@ssword');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'MyISAM');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'H3RyU5jK6TegDXs2enGTENvSihGvDfxbdqCA46v5NG2Mujaqd61mRZcJ');
define('_COOKIE_IV_', 'ResDYeia');
define('_PS_CREATION_DATE_', '2014-10-04');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'bhLHkCNucc0UBavfj0cIKBEQAvOVrFJa');
define('_RIJNDAEL_IV_', '/VGG7bnX2nncR7xu4LwGHQ==');
